### ISSUE TITLE
[BUG]npm start后出错见截图

### ISSUE THREAD

**Issue by zengfr** [DevCloudFE/ng-devui-admin#10]
** **
安装
全局 Angular cli
npm i -g @angular/cli@11
创建 DevUI Admin 项目
创建一个新的项目

ng new your-project && cd your-project
添加 DevUI Admin 项目

ng add ng-devui-admin
运行
npm start
![image](https://user-images.githubusercontent.com/9524903/120584492-ab04f500-c462-11eb-9d39-164b668c27b9.png)

![image](https://user-images.githubusercontent.com/9524903/120584356-6bd6a400-c462-11eb-8c03-57257d9403a2.png)

**Comment by zengfr** [comment]
![image](https://user-images.githubusercontent.com/9524903/120592794-01793000-c471-11eb-803a-1ce957533533.png)

**Comment by GreatZPP** [comment]
从截图报错看，可排查你的项目是否为使用cli@12版本创建

使用 npm i -g @angular/cli@11，全局安装11版本cli

**Comment by zengfr** [comment]
npm i -g @angular/cli@11 切到11后 
npm start  还是一样
![image](https://user-images.githubusercontent.com/9524903/120613074-7310a880-c488-11eb-8389-ea6b73878bcb.png)

**Comment by GreatZPP** [comment]
重新install cli后 需要重新使用cli新建一个项目 安装对应版本依赖哦

**Comment by zengfr** [comment]
是的。 除了 cli@11 其他都是最新的版本， 清空目录， 清空缓存全新安装的。
应该是npm 7最新的问题， 还有一个可能是amd  cpu 有提示警告 。
----------------------
npm 7中引入的一项新功能是自动安装peer dependencies。在npm的之前版本（4-6）中，peer dependencies冲突会有版本不兼容的警告，但仍会安装依赖并不会抛出错误。在npm 7中，如果存在无法自动解决的依赖冲突，将会阻止安装。

可以通过使--force选项重新安装来绕过冲突，或者选择--legacy-peer-deps选项peer dependencies的依赖关系（类似于npm版本4-6）。

由于许多包都依赖宽松的peer dependencies解析，npm 7将打印警告并解决包依赖树中存在的大多数同级冲突，因此这些冲突不能手动处理。要在所有层级强制执行严格正确的peer dependencies依赖关系，请使用--strict-peer-deps选项。

**Comment by zengfr** [comment]
加 --force 解决了
