### ISSUE TITLE
devui建议添加代码混淆可配置步骤和方法

### ISSUE THREAD

**Issue by zengfr** [DevCloudFE/ng-devui-admin#13]
quickstart或常见问题doc中
建议添加代码混淆可配置步骤和方法供参考 
谢谢 网上没找到靠谱的
https://devui.design/admin-page/docs/getting-started
https://devui.design/admin-page/docs/faq

**Comment by GreatZPP** [comment]
可尝试先在package.json中做以下修改，给build加上--prod选项：
```
"scripts": {
  ...
  "build": "ng build --prod",
  ...
```

我们将在后续版本中对文档进行更新。

**Comment by xiejay97** [comment]
代码混淆不是为了加密商业源码吗, js 作为解释型语言, 混淆没多大意义, 太容易破解了

**Comment by ricenoddle** [comment]
> 代码混淆不是为了加密商业源码吗, js 作为解释型语言, 混淆没多大意义, 太容易破解了

可以参考一下官网https://angular.cn/guide/deployment，一般来说 --prod就会帮你做代码混淆了
