### ISSUE TITLE
建议大量强化list table的搜索功能,搜索是重点要点关键点

### ISSUE THREAD

**Issue by zengfr** [DevCloudFE/ng-devui-admin#14]
如题

**Comment by GreatZPP** [comment]
在我们实践中，一般的策略会是经过后端接口进行数据的搜索
故当前如果在前端加强搜索，可能不适用于普遍的一种场景

**Comment by zengfr** [comment]
目前看 表格的 搜索查询和编辑的交互太弱了些 交互有些也非最佳实践
建议多来些交互经典案例

**Comment by GreatZPP** [comment]
可以的，这个后续我们可以优化
我们在后续版本中将把项目中各个区块进行拆分统一管理，届时大家也可进行区块的贡献~
