### ISSUE TITLE
npm 版本未和现有 release 版本同步

### ISSUE THREAD

**Issue by LstHeart** [DevCloudFE/ng-devui-admin#15]
现在 release 版本是1.2.0，但 npm 的版本好像还停留在 1.0.1；
麻烦更新一下😁

**Comment by ricenoddle** [comment]
> 现在 release 版本是1.2.0，但 npm 的版本好像还停留在 1.0.1；
> 麻烦更新一下😁

嗯我们将会在下个版本一起同步一下，目前npm版本还有一些问题在修改
