### ISSUE TITLE
[BUG]路由错误，导致新建的页面和区块访问不了

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/ng-devui-admin#19]
# 复现步骤

1. 在`src/app/pages`目录下新建一个页面
```
ng g ng-devui-admin:views --view-name test-page-setting
```
2. 交互式命令行中随便选择一个区块，比如`CardList`，并选择需要创建左侧导航
3. 在页面中点击该导航，预期应该跳转新创建的卡片列表页面，实际跳转到示例页面，如下图：

![输入图片说明](https://images.gitee.com/uploads/images/2021/1002/183334_eb4c74db_7746958.png "屏幕截图.png")

# 问题原因

怀疑是以下原因之一导致的：
1. 左侧导航链接错误
2. 路由配置错误

**Comment by ricenoddle** [comment]
文档中已更新相关问题
