### ISSUE TITLE
[BUG]ng add ng-devui-admin时报错

### ISSUE THREAD

**Issue by adi100** [DevCloudFE/ng-devui-admin#29]
**Describe the bug**
Skipping installation: Package already installed
? Please choose the default language you want to use:  简体中文 (zh-ch)
? Would you like to add lint files for your project? (default: Y) Yes
? Would you like to add mock module? (default: Y) Yes
? Would you like to add i18n? (default: Y) Yes
**Cannot read properties of undefined (reading 'sourceRoot')**
"@angular/cli": "~15.2.1"

**To Reproduce**

**Expected behavior**

**Screenshots**

**environments (please complete the following information):**
 - Browser [e.g. chrome 80, safari]
 - component version [e.g. 8.0.0]
 - angular framework version [e.g. 8.0.0]

**Additional context**

**Comment by chenxiang0010** [comment]
一样的问题
