### ISSUE TITLE
[BUG]Cannot read properties of undefined (reading 'sourceRoot')

### ISSUE THREAD

**Issue by 75910456** [DevCloudFE/ng-devui-admin#31]
>ng version
Angular CLI: 15.2.6
Node: 18.16.0
Package Manager: npm 9.5.1

>ng add ng-devui-admin
The package ng-devui-admin@15.0.0 will be installed and executed.
Would you like to proceed? Yes
√ Packages successfully installed.
? Please choose the default language you want to use:  简体中文 (zh-ch)
? Would you like to add lint files for your project? (default: Y) Yes
? Would you like to add mock module? (default: Y) No
? Would you like to add i18n? (default: Y) No
Cannot read properties of undefined (reading 'sourceRoot')

**Comment by ricenoddle** [comment]
因为 ng15 的 angular.json 里面移除了 sourceRoot，下个版本修复，可以先clone项目进行使用

**Comment by andresave7** [comment]
Hello, I am having the same issue. I am able to build it with Angular 12;However, I am wondering if a fix to use Angular 16 is coming soon ( this particular bug). I am looking forward to use the lib in a production environment. I would like to start with the latest and greatest.

**Comment by ricenoddle** [comment]
该问题已经修改，当前最新版本 ng-devui-admin@15.1.0

**Comment by ricenoddle** [comment]
该问题已经修改，当前最新版本 ng-devui-admin@15.1.0，schematics代码我们将会同步到此 @summersmile1984 
Hello, we have fixed this issue, and for now we only support angular15, thanks. @andresave7
