### ISSUE TITLE
[BUG] ENOENT: no such file or directory, open 'xxxxxx/node_modules/tsconfig.json'

### ISSUE THREAD

**Issue by soulary233** [DevCloudFE/ng-devui-admin#32]
Angular CLI: 15.2.7
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin arm64 
macOS Monterey,  MacBook Air M1

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.7
@angular-devkit/build-angular   15.2.7
@angular-devkit/core            15.2.7
@angular-devkit/schematics      15.2.7
@angular/cli                    15.2.7
@schematics/angular             15.2.7
rxjs                            7.5.7
typescript                      4.9.5

1. 在新建项目下执行```ng add ng-devui-admin```
The package ng-devui-admin@15.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
? Please choose the default language you want to use:  简体中文 (zh-ch)
? Would you like to add lint files for your project? (default: Y) Yes
? Would you like to add mock module? (default: Y) Yes
? Would you like to add i18n? (default: Y) Yes
```Cannot read properties of undefined (reading 'sourceRoot')```

2.  在```angular.json```文件添加defaultProject属性，解决步骤1的sourceRoot问题，再次执行```ng add ng-devui-admin```
Skipping installation: Package already installed
? Please choose the default language you want to use:  简体中文 (zh-ch)
? Would you like to add lint files for your project? (default: Y) Yes
? Would you like to add mock module? (default: Y) Yes
? Would you like to add i18n? (default: Y) Yes
```ENOENT: no such file or directory, open 'xxxxxx/node_modules/tsconfig.json'```
(xxxxxx是项目的文件路径)

**Comment by yun-zero** [comment]
> 2\. defaultProject

在angular.json文件添加defaultProject属性这个具体怎么做？。ENOENT: no such file or directory, open 'xxxxxx/node_modules/tsconfig.json'

**Comment by soulary233** [comment]
> > 2. defaultProject
> 
> 在angular.json文件添加defaultProject属性这个具体怎么做？。第二个问题：ENOENT: no such file or directory, open 'xxxxxx/node_modules/tsconfig.json'。可以吧当前目录到tsconfig.json拷贝到项目的node_modules里面

1. defaultProject属性，参考的 https://github.com/DevCloudFE/ng-devui/issues/255
```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "defaultProject": "your-project-name",
  "newProjectRoot": "projects",
  "projects": {
    ......
  }
}
```
2. ```tsconfig.json```问题，我最后直接把文件复制到```node_modules```目录下面，可以执行成功  😄

**Comment by 18073479643** [comment]
> > > 2. 默认项目
> > 
> > 
> > 在angular.json文件添加defaultProject属性这个具体怎么做？。第二个问题：ENOENT: no such file or directory, open 'xxxxxx/node_modules/tsconfig.json'。可以吧当前目录到tsconfig.json复制到项目的node_modules里面
> 
> 1. defaultProject 属性，参考的[无法读取未定义的属性（读取 'sourceRoot'）](https://github.com/DevCloudFE/ng-devui/issues/255)[ ng-devui#255](https://github.com/DevCloudFE/ng-devui/issues/255)[](https://github.com/DevCloudFE/ng-devui/issues/255)
> 
> ```json
> {
>   "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
>   "version": 1,
>   "defaultProject": "your-project-name",
>   "newProjectRoot": "projects",
>   "projects": {
>     ......
>   }
> }
> ```
> 
> 2. `tsconfig.json`问题，我最后直接把文件复制到`node_modules`目录下面，可以执行成功  😄

还是不行
1.在angular.json文件添加defaultProject属性，会得到黄色字体警告"Workspace extension with invalid name (defaultProject) found."
2.无视第一个警告，继续执行下面的，会得到报错“ENOENT: no such file or directory, open 'D:\ng\demo\node_modules\tsconfig.json'”
3.按照你的方法，直接把文件复制到node_modules目录下面，虽然一开始可以正常执行，但是到最后还是会出现npm报错，最终导致项目无法创建
第三步中npm报错具体信息：UPDATE src/app/app.component.ts (577 bytes)
UPDATE src/app/app.module.ts (1163 bytes)
⠼ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: demo@0.0.0
npm ERR! Found: @angular/animations@16.1.4
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"^16.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^15.0.0" from ng-devui@15.1.0
npm ERR! node_modules/ng-devui
npm ERR!   ng-devui@"^15.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Administrator\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-07-12T08_29_03_123Z-debug-0.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

**Comment by soulary233** [comment]
> > > > 2. 默认项目
> > > 
> > > 
> > > 在angular.json文件添加defaultProject属性这个具体怎么做？。第二个问题：ENOENT: no such file or directory, open 'xxxxxx/node_modules/tsconfig.json'。可以吧当前目录到tsconfig.json复制到项目的node_modules里面
> > 
> > 
> > 
> > 1. defaultProject 属性，参考的[无法读取未定义的属性（读取 'sourceRoot'）](https://github.com/DevCloudFE/ng-devui/issues/255)[ ng-devui#255](https://github.com/DevCloudFE/ng-devui/issues/255)
> > 
> > ```json
> > {
> >   "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
> >   "version": 1,
> >   "defaultProject": "your-project-name",
> >   "newProjectRoot": "projects",
> >   "projects": {
> >     ......
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. `tsconfig.json`问题，我最后直接把文件复制到`node_modules`目录下面，可以执行成功  😄
> 
> 还是不行 1.在angular.json文件添加defaultProject属性，会得到黄色字体警告"Workspace extension with invalid name (defaultProject) found." 2.无视第一个警告，继续执行下面的，会得到报错“ENOENT: no such file or directory, open 'D:\ng\demo\node_modules\tsconfig.json'” 3.按照你的方法，直接把文件复制到node_modules目录下面，虽然一开始可以正常执行，但是到最后还是会出现npm报错，最终导致项目无法创建 第三步中npm报错具体信息：UPDATE src/app/app.component.ts (577 bytes) UPDATE src/app/app.module.ts (1163 bytes) ⠼ Installing packages (npm)...npm ERR! code ERESOLVE npm ERR! ERESOLVE unable to resolve dependency tree npm ERR! npm ERR! While resolving: demo@0.0.0 npm ERR! Found: @angular/animations@16.1.4 npm ERR! node_modules/@angular/animations npm ERR! @angular/animations@"^16.1.0" from the root project npm ERR! npm ERR! Could not resolve dependency: npm ERR! peer @angular/animations@"^15.0.0" from ng-devui@15.1.0 npm ERR! node_modules/ng-devui npm ERR! ng-devui@"^15.0.0" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force, or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution. npm ERR! npm ERR! See C:\Users\Administrator\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Administrator\AppData\Local\npm-cache_logs\2023-07-12T08_29_03_123Z-debug-0.log ✖ Package install failed, see above. The Schematic workflow failed. See above.

你项目的依赖版本有冲突吧，用的angular cli版本是多少？16吗?

**Comment by wangkailun** [comment]
官方有修复这个问题吗？

**Comment by 18073479643** [comment]
> > > > > 2. 预设项目
> > > > 
> > > > 
> > > > 在angular.json文件中添加defaultProject属性这个具体怎么做？。第二个问题：ENOENT: no such file or directory, open 'xxxxxx/node_modules/tsconfig.json'。可以吧当前目录到tsconfig.json复制到项目的node_modules里面
> > > 
> > > 
> > > 
> > > 1. defaultProject 属性，参考[无法读取未定义的属性（读取 'sourceRoot'）](https://github.com/DevCloudFE/ng-devui/issues/255)[ ng-devui#255](https://github.com/DevCloudFE/ng-devui/issues/255)
> > > 
> > > ```json
> > > {
> > >   "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
> > >   "version": 1,
> > >   "defaultProject": "your-project-name",
> > >   "newProjectRoot": "projects",
> > >   "projects": {
> > >     ......
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 2. `tsconfig.json`问题，我最后直接把文件复制到`node_modules`目录下面，可以执行成功  😄
> > 
> > 
> > 还是不行 1.在angular.json文件中添加defaultProject属性，会得到字体警告“发现工作空间扩展名无效(defaultProject)。” 2.无视第一个警告，继续执行下面的，会得到报错“ENOENT: no such file or directory, open 'D:\ng\demo\node_modules\tsconfig.json'” 3.按照你的方法，直接把文件复制到node_modules目录下面但是一开始可以正常执行，到最后还是会出现npm报错，导致项目最终无法创建第三步中npm报错具体信息：UPDATE src/app/app.component.ts (577 bytes) ) 更新 src/app/app.module.ts (1163 字节) ⠼ 安装软件包 (npm)...npm 错误！代码 ERESOLVE npm 错误！ERESOLVE 无法解析依赖树 npm 错误！npm 错误！解决时：demo@0.0.0 npm ERR！发现：@angular/animations@16.1.4 npm 错误！node_modules/@angular/animations npm 错误！@angular/animations@"^16.1.0" 来自根项目 npm 错误！npm 错误！无法解决依赖关系：npm ERR！来自 ng-devui@15.1.0 的同行 @angular/animations@"^15.0.0" npm 错误！node_modules/ng-devui npm 错误！ng-devui@"^15.0.0" 来自根项目 npm 错误！npm 错误！修复上游依赖冲突，或者重试npm ERR！此命令带有 --force 或 --legacy-peer-deps npm ERR！接受不正确的（并且可能损坏的）依赖关系解析。npm 错误！npm 错误！有关完整报告，请参阅 C:\Users\Administrator\AppData\Local\npm-cache\eresolve-report.txt。
> > npm 错误！可以在以下位置找到此运行的完整日志：npm ERR！C:\Users\Administrator\AppData\Local\npm-cache_logs\2023-07-12T08_29_03_123Z-debug-0.log✖软件包安装失败，请参见上文。原理图工作流程失败。往上看。
> 
> 你项目的依赖版本有冲突吧，用的Angular cli版本是多少？16吗？

我在16和12这个两个版本都有使用过，均有上述问题。如果没有好的解决办法，能否提供一个空的项目供我们拉取使用(就是你创建好，然后发布，我们直接拉取，无需自己创建)

**Comment by soulary233** [comment]
> > > > > > 2. 预设项目
> > > > > 
> > > > > 
> > > > > 在angular.json文件中添加defaultProject属性这个具体怎么做？。第二个问题：ENOENT: no such file or directory, open 'xxxxxx/node_modules/tsconfig.json'。可以吧当前目录到tsconfig.json复制到项目的node_modules里面
> > > > 
> > > > 
> > > > 
> > > > 1. defaultProject 属性，参考[无法读取未定义的属性（读取 'sourceRoot'）](https://github.com/DevCloudFE/ng-devui/issues/255)[ ng-devui#255](https://github.com/DevCloudFE/ng-devui/issues/255)
> > > > 
> > > > ```json
> > > > {
> > > >   "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
> > > >   "version": 1,
> > > >   "defaultProject": "your-project-name",
> > > >   "newProjectRoot": "projects",
> > > >   "projects": {
> > > >     ......
> > > >   }
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 
> > > > 2. `tsconfig.json`问题，我最后直接把文件复制到`node_modules`目录下面，可以执行成功  😄
> > > 
> > > 
> > > 还是不行 1.在angular.json文件中添加defaultProject属性，会得到字体警告“发现工作空间扩展名无效(defaultProject)。” 2.无视第一个警告，继续执行下面的，会得到报错“ENOENT: no such file or directory, open 'D:\ng\demo\node_modules\tsconfig.json'” 3.按照你的方法，直接把文件复制到node_modules目录下面但是一开始可以正常执行，到最后还是会出现npm报错，导致项目最终无法创建第三步中npm报错具体信息：UPDATE src/app/app.component.ts (577 bytes) ) 更新 src/app/app.module.ts (1163 字节) ⠼ 安装软件包 (npm)...npm 错误！代码 ERESOLVE npm 错误！ERESOLVE 无法解析依赖树 npm 错误！npm 错误！解决时：demo@0.0.0 npm ERR！发现：@angular/animations@16.1.4 npm 错误！node_modules/@angular/animations npm 错误！@angular/animations@"^16.1.0" 来自根项目 npm 错误！npm 错误！无法解决依赖关系：npm ERR！来自 ng-devui@15.1.0 的同行 @angular/animations@"^15.0.0" npm 错误！node_modules/ng-devui npm 错误！ng-devui@"^15.0.0" 来自根项目 npm 错误！npm 错误！修复上游依赖冲突，或者重试npm ERR！此命令带有 --force 或 --legacy-peer-deps npm ERR！接受不正确的（并且可能损坏的）依赖关系解析。npm 错误！npm 错误！有关完整报告，请参阅 C:\Users\Administrator\AppData\Local\npm-cache\eresolve-report.txt。
> > > npm 错误！可以在以下位置找到此运行的完整日志：npm ERR！C:\Users\Administrator\AppData\Local\npm-cache_logs\2023-07-12T08_29_03_123Z-debug-0.log✖软件包安装失败，请参见上文。原理图工作流程失败。往上看。
> > 
> > 
> > 你项目的依赖版本有冲突吧，用的Angular cli版本是多少？16吗？
> 
> 我在16和12这个两个版本都有使用过，均有上述问题。如果没有好的解决办法，能否提供一个空的项目供我们拉取使用(就是你创建好，然后发布，我们直接拉取，无需自己创建)

你为什么不用版本15😂

**Comment by 18073479643** [comment]
> > > > > > > 2. 项目基地
> > > > > > 
> > > > > > 
> > > > > > 在angular.json文件中添加defaultProject属性这个具体怎么做？。第二个问题：ENOENT: no such file or directory, open 'xxxxxx/node_modules/tsconfig.json'。可以吧当前目录到tsconfig.json复制到项目的node_modules里面
> > > > > 
> > > > > 
> > > > > 
> > > > > 1. defaultProject 属性，参考[无法读取未定义的属性（读取 'sourceRoot'）](https://github.com/DevCloudFE/ng-devui/issues/255)[ ng-devui#255](https://github.com/DevCloudFE/ng-devui/issues/255)
> > > > > 
> > > > > ```json
> > > > > {
> > > > >   "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
> > > > >   "version": 1,
> > > > >   "defaultProject": "your-project-name",
> > > > >   "newProjectRoot": "projects",
> > > > >   "projects": {
> > > > >     ......
> > > > >   }
> > > > > }
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 
> > > > > 2. `tsconfig.json`问题，我最后直接把文件复制到`node_modules`目录下面，可以执行成功  😄
> > > > 
> > > > 
> > > > 还是不行 1.在angular.json文件中添加defaultProject属性，会得到字体警告“下面找到工作空间扩展名无效(defaultProject)。” 2.无视第一个警告，继续执行的，会得到错误“ENOENT: no这样的文件或目录，打开 'D:\ng\demo\node_modules\tsconfig.json'” 3.按照你的方法，直接把文件复制到node_modules目录下面但是一开始可以正常执行，到最后还是会出现npm报错，导致项目最终无法创建第三步中 npm 报错具体信息：更新 src/app/app.component.ts (577 bytes) ) 更新 src/app/app.module.ts (1163 字节) ⠼ 安装模块 ( npm)...npm 错误！代码 ERESOLVE npm 错误！ERESOLVE 无法解析依赖树 npm 错误！npm 错误！解决时：demo@0.0.0 npm ERR！发现：@angular/animations@16.1.4 npm 错误！node_modules/ @angular/animations npm 错误！@angular/animations@"^16.1.0" 来自根项目 npm 错误！npm 错误！无法解决依赖关系：npm ERR！来自 ng-devui@15.1.0 的同行 @angular/animations@ "^15.0.0" npm 错误！node_modules/ng-devui npm 错误！ng-devui@"^15.0.0" 来自根项目 npm 错误！npm 错误！修复上游依赖冲突，或者重试 npm ERR！此命令带有 --force 或 --legacy-peer-deps npm ERR！接受不正确的（并且可能损坏的）依赖关系解析。npm 错误！npm 错误！有关完整报告，请参阅 C:\Users\Administrator\AppData\Local\npm-cache\eresolve-report.txt。
> > > > npm 错误！可以在以下位置找到此运行的完整日志：npm ERR！C:\Users\Administrator\AppData\Local\npm-cache_logs\2023-07-12T08_29_03_123Z-debug-0.log✖全部安装失败，请参见全部。原理图工作流程失败。往上看。
> > > 
> > > 
> > > 你项目的依赖版本有冲突吧，用的Angular cli版本是多少？16吗？
> > 
> > 
> > 我在16和12这两个版本都有使用过，导致上述问题。如果没有好的解决办法，能否提供一个空的项目我们供拉取使用（就是你创建好，然后发布，我们直接拉取，耗费自己创建）
> 
> 你为什么不用版本15😂

官网都显示的都是用的12版。用了15版本确实是可以构建成功，但是里面有代码个导入报错，import { environment } from './environments/environment我查看了，也确实没这个文件。注释掉就成功运行了。但是我想问，这个直接注释会有什么影响吗，这个文件是干什么的？有什么好的解决办法没有

**Comment by soulary233** [comment]
> 



> > > > > > > > 2. 项目基地
> > > > > > > 
> > > > > > > 
> > > > > > > 在angular.json文件中添加defaultProject属性这个具体怎么做？。第二个问题：ENOENT: no such file or directory, open 'xxxxxx/node_modules/tsconfig.json'。可以吧当前目录到tsconfig.json复制到项目的node_modules里面
> > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 1. defaultProject 属性，参考[无法读取未定义的属性（读取 'sourceRoot'）](https://github.com/DevCloudFE/ng-devui/issues/255)[ ng-devui#255](https://github.com/DevCloudFE/ng-devui/issues/255)
> > > > > > 
> > > > > > ```json
> > > > > > {
> > > > > >   "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
> > > > > >   "version": 1,
> > > > > >   "defaultProject": "your-project-name",
> > > > > >   "newProjectRoot": "projects",
> > > > > >   "projects": {
> > > > > >     ......
> > > > > >   }
> > > > > > }
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 
> > > > > > 2. `tsconfig.json`问题，我最后直接把文件复制到`node_modules`目录下面，可以执行成功  😄
> > > > > 
> > > > > 
> > > > > 还是不行 1.在angular.json文件中添加defaultProject属性，会得到字体警告“下面找到工作空间扩展名无效(defaultProject)。” 2.无视第一个警告，继续执行的，会得到错误“ENOENT: no这样的文件或目录，打开 'D:\ng\demo\node_modules\tsconfig.json'” 3.按照你的方法，直接把文件复制到node_modules目录下面但是一开始可以正常执行，到最后还是会出现npm报错，导致项目最终无法创建第三步中 npm 报错具体信息：更新 src/app/app.component.ts (577 bytes) ) 更新 src/app/app.module.ts (1163 字节) ⠼ 安装模块 ( npm)...npm 错误！代码 ERESOLVE npm 错误！ERESOLVE 无法解析依赖树 npm 错误！npm 错误！解决时：demo@0.0.0 npm ERR！发现：@angular/animations@16.1.4 npm 错误！node_modules/ @angular/animations npm 错误！@angular/animations@"^16.1.0" 来自根项目 npm 错误！npm 错误！无法解决依赖关系：npm ERR！来自 ng-devui@15.1.0 的同行 @angular/animations@ "^15.0.0" npm 错误！node_modules/ng-devui npm 错误！ng-devui@"^15.0.0" 来自根项目 npm 错误！npm 错误！修复上游依赖冲突，或者重试 npm ERR！此命令带有 --force 或 --legacy-peer-deps npm ERR！接受不正确的（并且可能损坏的）依赖关系解析。npm 错误！npm 错误！有关完整报告，请参阅 C:\Users\Administrator\AppData\Local\npm-cache\eresolve-report.txt。
> > > > > npm 错误！可以在以下位置找到此运行的完整日志：npm ERR！C:\Users\Administrator\AppData\Local\npm-cache_logs\2023-07-12T08_29_03_123Z-debug-0.log✖全部安装失败，请参见全部。原理图工作流程失败。往上看。
> > > > 
> > > > 
> > > > 你项目的依赖版本有冲突吧，用的Angular cli版本是多少？16吗？
> > > 
> > > 
> > > 我在16和12这两个版本都有使用过，导致上述问题。如果没有好的解决办法，能否提供一个空的项目我们供拉取使用（就是你创建好，然后发布，我们直接拉取，耗费自己创建）
> > 
> > 
> > 你为什么不用版本15😂
> 
> 官网都显示的都是用的12版。用了15版本确实是可以构建成功，但是里面有代码个导入报错，import { environment } from './environments/environment我查看了，也确实没这个文件。注释掉就成功运行了。但是我想问，这个直接注释会有什么影响吗，这个文件是干什么的？有什么好的解决办法没有

官方现在最新也是15吧，我用的angular cli版本是15.2.7，默认不会在新建的工程下自动生成```environments```目录，需要执行```ng generate environments```，并在```environment-*.ts```文件里添加```production```属性。

```environment-*.ts```文件类似spring boot工程的```application.properties```，不同环境（如开发、测试、生产）对应不同的参数配置文件

**Comment by ricenoddle** [comment]
该问题已经修改，当前最新版本 ng-devui-admin@15.1.0
