### ISSUE TITLE
error TS2339: Property 'devuiThemes'

### ISSUE THREAD

**Issue by pschen** [DevCloudFE/ng-devui-admin#6]
Win10 +  node v14.15.4

![image](https://user-images.githubusercontent.com/5243355/118462960-cf0dca00-b731-11eb-8bfa-b3f2b889d79c.png)

ERROR in src/app/pages/pages.component.ts:86:51 - error TS2339: Property 'devuiThemes' does not exist on type 'Window & typeof globalThis'.
    86         const currentTheme = Object.values(window.devuiThemes).find((i: Theme) => {

**Comment by GreatZPP** [comment]
我们使用node14最新版本（V14.17.0） 使用yarn && yarn start （yarn v1.22.10）启动，typestcript@4.0.0，未出现截图中报错。
