### ISSUE TITLE
[BUG]根据文档操作无法运行，下列只是小部分错误，我是个后端。不太懂怎么修复，但是下载 克隆你们项目又没有问题

### ISSUE THREAD

**Issue by aimo-x** [DevCloudFE/ng-devui-admin#7]
Error: src/app/@shared/layouts/da-layout/da-layout.component.ts:241:9 - error TS2532: Object is possibly 'undefined'.

241     if (this.config.header.hidden) {
            ~~~~~~~~~~~~~~~~~~


Error: src/app/@shared/layouts/da-layout/da-layout.component.ts:245:10 - error TS2532: Object is possibly 'undefined'.

245     if (!this.config.header.firHeader.hidden) {
             ~~~~~~~~~~~~~~~~~~

Error: src/app/@shared/layouts/da-layout/da-layout.component.ts:245:10 - error TS2532: Object is possibly 'undefined'.

245     if (!this.config.header.firHeader.hidden) {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: src/app/@shared/layouts/da-layout/da-layout.component.ts:246:17 - error TS2532: Object is possibly 'undefined'.

246       height += this.config.header.firHeader.height;
                    ~~~~~~~~~~~~~~~~~~

**Comment by GreatZPP** [comment]
另外，如果你在使用我们DevUI过程中有任何其他问题，欢迎加入我们的官方讨论支撑群：
![image](https://user-images.githubusercontent.com/39985263/118487427-469d2280-b74d-11eb-9a29-64d25323d289.png)

**Comment by aimo-x** [comment]
好的
