### ISSUE TITLE
[BUG] 安装问题

### ISSUE THREAD

**Issue by liuliancao** [DevCloudFE/ng-devui-admin#8]
**Describe the bug**
安装admin成功，但是ng serve时候报错

**Step**
1. ng new xxx然后都是默认
2. ng add ng-devui-admin
UPDATE angular.json (3829 bytes)
UPDATE package.json (1699 bytes)
UPDATE src/favicon.ico (101332 bytes)
UPDATE src/index.html (321 bytes)
UPDATE src/main.ts (809 bytes)
UPDATE src/app/app-routing.module.ts (803 bytes)
UPDATE src/app/app.component.ts (534 bytes)
UPDATE src/app/app.module.ts (1151 bytes)
提示成功
3. ng serve报错

**Screenshots**

![image](https://user-images.githubusercontent.com/14558434/120136744-6deff700-c205-11eb-8ceb-f6bf30dffc26.png)

**环境**
@angular-devkit/architect    0.1102.13 (cli-only)
@angular-devkit/core         11.2.13 (cli-only)
@angular-devkit/schematics   11.2.13 (cli-only)
@schematics/angular          11.2.13 (cli-only)
@schematics/update           0.1102.13 (cli-only)

**Comment by liuliancao** [comment]
我是用css+strict初始化的

**Comment by liuliancao** [comment]
scss+nostrict可以 如果css+strict不行 麻烦更新下readme吧

**Comment by GreatZPP** [comment]
严格模式为ng cli小版本更新的选项，将在下个admin版本发布时适配，scss选项我们将在文档中进行说明
